title: Adam Becker
description: "writes code, rides bikes.<br />Oaklander in DC."

url: http://ada.mbecker.cc/wonderland
permalink: pretty

twitter: adamjacobbecker
github: adamjacobbecker
dribbble: rigoneri
lastfm: rigoneri
lastfm_api_key: e37e6ece4a103780c5dfddd4b95439bd
soundcloud: guram-kajaia
soundcloud_api_key: 08278390b588057b5a9bf9ff24c8fd84
soundcloud_show_artwork: false
instagram_id: 1574083

server: true
auto: true